# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
You do need my permission to make sure that I have a thou king for 8the sake and just the truth and I will never forgive you do you have any 

              Spanish Language en esto que tú piensas que no puedes hacer vencer Cómo saber si una persona en esta vida positiva y déjalo negativos y atrás como si nunca hubiera pasado Por qué la gente que está haciéndose mal es como si fuera uno el otro enemigo si no se puede así vivir
